version: '2'

services:
  mysql:
    image: mysql:5.6.39
    mem_limit: 512m
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    network_mode: bridge
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD:-root.123}
    volumes:
      - /mysql_data:/var/lib/mysql